name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static_analysis:
    name: Static Analysis with SpotBugs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run Checkers
        run: ./gradlew check

      # == Upload SpotBugs reports ==
      - name: Upload SpotBugs HTML reports
        uses: actions/upload-artifact@v4
        with:
          name: spotbugs-reports
          path: |
            app/build/reports/spotbugs/spotbugsDebug.html
            app/build/reports/spotbugs/spotbugsRelease.html

      # == Upload Android Lint report ==
      - name: Upload Android Lint HTML report
        uses: actions/upload-artifact@v4
        with:
          name: lint-report
          path: app/build/reports/lint-results-debug.html

      # == Upload Checkstyle report ==
      - name: Upload Checkstyle HTML report
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-report
          path: app/build/reports/checkstyle/main.html


  build_apk:
    name: Build APK
    needs: static_analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
      - name: Accept Android SDK Licenses
        run: |
          echo y | sdkmanager --licenses
      - name: Build APK
        run: ./gradlew assembleDebug
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug.apk
          path: app/build/outputs/apk/debug/app-debug.apk